### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Services.AsynchronousOperationException
  id: AsynchronousOperationException
  children:
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Exception)
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String)
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: AsynchronousOperationException
  nameWithType: AsynchronousOperationException
  fullName: System.IdentityModel.Services.AsynchronousOperationException
  type: Class
  summary: "Undantag som utlöses när ett fel uppstår under en asynkron åtgärd."
  syntax:
    content: 'public class AsynchronousOperationException : Exception'
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException()
  nameWithType: AsynchronousOperationException.AsynchronousOperationException()
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException()
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "Initierar en ny instans av den <xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;> </xref> klass."
  remarks: "Den här konstruktorn initierar den <xref:SystemException.Message>egenskapen för den nya instansen i ett meddelande som beskriver fel som tillhandahålls av systemet.</xref:SystemException.Message> Det här meddelandet tar hänsyn till den aktuella systemkulturen.       I följande tabell visas de inledande egenskapsvärdena för den nya instansen.      | Egenskapen | Värdet |   |--------------|-----------|   | <xref:System.Exception.InnerException>| `null`.|   | <xref:System.Exception.Message>| Den lokaliserade felsträngen meddelande. |</xref:System.Exception.Message> </xref:System.Exception.InnerException>"
  syntax:
    content: public AsynchronousOperationException ();
    parameters: []
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Exception)
  id: '#ctor(System.Exception)'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(Exception)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(Exception)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "Initierar en ny instans av den <xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;> </xref> klass med ett felmeddelande som tillhandahålls av systemet och en referens till det interna undantaget som är orsaken till det här undantaget."
  remarks: "Ett undantag som utlöses när ett direkt resultat av ett tidigare undantag ska innehålla en referens till det tidigare undantaget i den <xref:System.Exception.InnerException>egenskapen.</xref:System.Exception.InnerException> Den <xref:System.Exception.InnerException>-egenskap returnerar samma värde som skickades till konstruktorn.</xref:System.Exception.InnerException>       I följande tabell visas de inledande egenskapsvärdena för den nya instansen.      | Egenskapen | Värdet |   |--------------|-----------|   | <xref:System.Exception.InnerException>| Referens för inre undantag. |   | <xref:System.Exception.Message>| Ett meddelande som beskriver fel som tillhandahålls av systemet.</xref:System.Exception.Message> </xref:System.Exception.InnerException> Det här meddelandet tar hänsyn till den aktuella systemkulturen. |"
  syntax:
    content: public AsynchronousOperationException (Exception innerException);
    parameters:
    - id: innerException
      type: System.Exception
      description: "Den <xref:System.Exception>som är orsaken till det aktuella undantaget.</xref:System.Exception> Om den `innerException` parametern är inte <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, det aktuella undantaget utlöses i en <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> block som hanterar det interna undantaget."
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(String)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(String)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "Initierar en ny instans av den <xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;> </xref> klass med ett angivet meddelande."
  remarks: "Den här konstruktorn initierar den <xref:System.Exception.Message>egenskapen för den nya undantag med hjälp av den `message` parameter.</xref:System.Exception.Message> Innehållet i `message` är avsedd att tolkas av människor. Anroparen av den här konstruktorn är behövs för att säkerställa att den här strängen lokaliserade för den aktuella systemkulturen.       I följande tabell visas de inledande egenskapsvärdena för den nya instansen.      | Egenskapen | Värdet |   |--------------|-----------|   | <xref:System.Exception.InnerException>| `null`.|   | <xref:System.Exception.Message>| Meddelandet felsträng. |</xref:System.Exception.Message> </xref:System.Exception.InnerException>"
  syntax:
    content: public AsynchronousOperationException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Felmeddelandet som förklarar orsaken till undantaget."
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(SerializationInfo,StreamingContext)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "Initierar en ny instans av den <xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;> </xref> klass med serialiserade data."
  remarks: "Den här konstruktorn anropas under deserialisering till att fylla Undantagsobjektet som överförs via en dataström."
  syntax:
    content: protected AsynchronousOperationException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "En <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> objekt som innehåller objektdata som serialiserade."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "En <xref:System.Runtime.Serialization.StreamingContext>-objekt som innehåller detaljerad information om käll- och målservrar.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.IdentityModel.Services.AsynchronousOperationException
  langs:
  - csharp
  name: AsynchronousOperationException(String,Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String,Exception)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(String,Exception)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services
  summary: "Initierar en ny instans av den <xref href=&quot;System.IdentityModel.Services.AsynchronousOperationException&quot;> </xref> klass med ett angivet meddelande och en referens till det interna undantaget som är orsaken till det här undantaget."
  remarks: "Ett undantag som utlöses när ett direkt resultat av ett tidigare undantag ska innehålla en referens till det tidigare undantaget i den <xref:System.Exception.InnerException>egenskapen.</xref:System.Exception.InnerException> Den <xref:System.Exception.InnerException>-egenskap returnerar samma värde som skickades till konstruktorn.</xref:System.Exception.InnerException>       I följande tabell visas de inledande egenskapsvärdena för den nya instansen.      | Egenskapen | Värdet |   |--------------|-----------|   | <xref:System.Exception.InnerException>| Referens för inre undantag. |   | <xref:System.Exception.Message>| Meddelandet felsträng. |</xref:System.Exception.Message> </xref:System.Exception.InnerException>"
  syntax:
    content: public AsynchronousOperationException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Felmeddelandet som förklarar orsaken till undantaget."
    - id: innerException
      type: System.Exception
      description: "Den <xref:System.Exception>som är orsaken till det aktuella undantaget.</xref:System.Exception> Om den `innerException` parametern är inte <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, det aktuella undantaget utlöses i en <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> block som hanterar det interna undantaget."
  overload: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException()
  nameWithType: AsynchronousOperationException.AsynchronousOperationException()
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException()
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Exception)
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(Exception)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(Exception)
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String)
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(String)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(SerializationInfo,StreamingContext)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor(System.String,System.Exception)
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException(String,Exception)
  nameWithType: AsynchronousOperationException.AsynchronousOperationException(String,Exception)
  fullName: System.IdentityModel.Services.AsynchronousOperationException.AsynchronousOperationException(String,Exception)
- uid: System.IdentityModel.Services.AsynchronousOperationException.#ctor*
  parent: System.IdentityModel.Services.AsynchronousOperationException
  isExternal: false
  name: AsynchronousOperationException
  nameWithType: AsynchronousOperationException.AsynchronousOperationException
